// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOkE2mGZdOePZUuKnM8s-6OIadOHiu9CE',
    appId: '1:888497741298:web:79d8aac5be12c69221df6b',
    messagingSenderId: '888497741298',
    projectId: 'culinarytalesapp',
    authDomain: 'culinarytalesapp.firebaseapp.com',
    databaseURL: 'https://culinarytalesapp-default-rtdb.firebaseio.com',
    storageBucket: 'culinarytalesapp.firebasestorage.app',
    measurementId: 'G-SWP6CX1E3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkE2mGZdOePZUuKnM8s-6OIadOHiu9CE',
    appId:
        '1:888497741298:android:79d8aac5be12c69221df6b', // Note: Placeholder appId
    messagingSenderId: '888497741298',
    projectId: 'culinarytalesapp',
    databaseURL: 'https://culinarytalesapp-default-rtdb.firebaseio.com',
    storageBucket: 'culinarytalesapp.firebasestorage.app',
  );
}
